# Generated by Django 4.0.4 on 2022-05-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee'), ('client', 'Client')], default='manager', max_length=50),
        ),
    ]
